// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package local

import (
	"Distributed-Cache/local/lru"
)

// Injectors from wire.go:

func WireCache(maxBytes lru.MaxBytes) *Cache {
	cache := lru.New(maxBytes)
	localCache := NewCache(cache)
	return localCache
}
