// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package distribute

import (
	"Distributed-Cache/distribute/consistentHash"
)

// Injectors from wire.go:

func WireCache(replicas consistentHash.Replicas, fn consistentHash.Hash, batch Batch, poolSize PoolSize) (*Cache, error) {
	consistentHashMap := consistentHash.New(replicas, fn)
	peerManager, err := NewPeerManager(consistentHashMap, batch, poolSize)
	if err != nil {
		return nil, err
	}
	cache := NewCache(peerManager)
	return cache, nil
}
